Adding efit02er and rfile tests and some minor cleanup.  Tests are more robust to repeat runs.

diff --git a/test/run_efit.sh.in b/test/run_efit.sh.in
--- a/test/run_efit.sh.in
+++ b/test/run_efit.sh.in
@@ -1,9 +1,19 @@
 #!/bin/bash
-SRCDIR=@CMAKE_CURRENT_SOURCE_DIR@
+if ! test -e @CMAKE_BINARY_DIR@/dprobe.dat; then
+  echo "not running test because Greens tables were not found"
+  exit 1
+fi
+
+for prefix in a g; do
+  if test -e ${prefix}@EFIT_LABEL@; then
+      rm ${prefix}@EFIT_LABEL@
+  fi
+done
+
 @EFIT_EXEC@ @GRID_SIZE@ << __c__MATCHING_EOF__c__
 @EFIT_MODE@
 @EFIT_TIME@
-k@EFIT_LABEL@
+@EFIT_IN@
 
 __c__MATCHING_EOF__c__
 
@@ -11,8 +21,9 @@ __c__MATCHING_EOF__c__
 # Now check to see if files exist
 
 for prefix in a g; do
-    if ! test -e ${prefix}@EFIT_LABEL@; then
-        exit 1
-    fi
+  if ! test -e ${prefix}@EFIT_LABEL@; then
+      exit 1
+  fi
 done
 
+# TO DO: compare results to reference output
