Adding a new namelist and restructuring code

diff --git a/test/run_efit.sh.in b/test/run_efit.sh.in
--- a/test/run_efit.sh.in
+++ b/test/run_efit.sh.in
@@ -7,22 +7,18 @@ export link_store=""
 export OMP_NUM_THREADS=1
 
 # Sanity checks
-if ! test -e ${link_efit}/green/dprobe.dat; then
-  echo "not running test because Greens tables were not found"
-  exit 1
-fi
-if ! test -e ${link_efit}/lim.dat; then
-  echo "not running test because limiter was not found"
-  exit 1
-fi
+#if ! test -e ${link_efit}/green/dprobe.dat; then
+#  echo "not running test because Greens tables were not found"
+#  exit 1
+#fi
+#if ! test -e ${link_efit}/lim.dat; then
+#  echo "not running test because limiter was not found"
+#  exit 1
+#fi
 
 # Remove any previous outputs
-if [ @HAVE_NETCDF@ = True ]; then
-  outputs=( a g m )
-else
-  outputs=( a g )
-fi
 rm -f run_efit.out
+outputs=( @EFIT_OUTPUTS@ )
 for prefix in ${outputs[*]}; do
   for label in @EFIT_LABEL@; do
     rm -f ${prefix}${label}
@@ -33,7 +29,7 @@ done
 @MPICMD@ @NPROC@ @EFIT_EXEC@ @GRID_SIZE@ << __c__MATCHING_EOF__c__ > run_efit.out
 
 @EFIT_MODE@
-@EFIT_TIME@
+@EFIT_COUNT@
 @EFIT_IN@
 
 __c__MATCHING_EOF__c__
